- hosts: local

  tasks:
  - name: Install packages
    apt: 
      name: ['bc','neovim','gawk','git','zsh','htop','aptitude','mtr','curl','dnsutils','most','mosh','nmap','netcat-openbsd','tmux','traceroute','wget','openvpn', 'silversearcher-ag', 'fd-find', 'direnv','python3-neovim']
      state: present 
      update_cache: yes
  - name: Check default editor
    stat: path=/etc/alternatives/editor
    register: editor
  - name: Set nvim as the default editor
    shell: "/usr/sbin/update-alternatives --set editor /usr/bin/nvim || /usr/bin/update-alternatives --set editor /usr/bin/nvim"
    when: editor.stat.lnk_source != '/usr/bin/nvim'
    #  - name: Install or update starship
    #shell: "curl -sS https://starship.rs/install.sh | sh -s -- -y"
