- hosts: local

  tasks:
  - name: Install packages
    apt: 
      name: ['neovim','gawk','git','zsh','htop','aptitude','mtr','curl','dnsutils','most','mosh','nmap','netcat-openbsd','tmux','traceroute','wget']
      state: present 
      update_cache: yes
