- hosts: local

  tasks:
  - name: Install packages
    apt: 
      name: ['snapd','bc','gawk','git','zsh','htop','aptitude','mtr','curl','dnsutils','most','mosh','nmap','netcat-openbsd','tmux','traceroute','wget','openvpn', 'silversearcher-ag', 'fd-find', 'direnv','python3-neovim']
      state: present 
      update_cache: yes
  - name: Check default editor
    stat: path=/etc/alternatives/editor
    register: editor
  - name: ensure neovim is not there 
    apt:
      name: ['neovim']
      state: absent
  - name: install neovim snap
    community.general.snap:
      name: nvim
      classic: true
  - name: Set nvim as the default editor
    shell: "/usr/sbin/update-alternatives --set editor /snap/nvim/bin/nvim || /usr/bin/update-alternatives --set editor /snap/nvim/bin/nvim"
    when: editor.stat.lnk_source != '/usr/bin/nvim'
    #  - name: Install or update starship
    #shell: "curl -sS https://starship.rs/install.sh | sh -s -- -y"
